jaffle_shop:
  outputs:
    dev:
      type: bigquery
      method: service-account
      keyfile: C:\Users\bjorn.bergdahl\.dbt\tough-cider-449414-c7-192477a844f7.json # replace this with the full path to your keyfile
      project: tough-cider-449414-c7 # Replace this with your project id
      dataset: dbt_molnet # Replace this with dbt_your_name, e.g. dbt_bilbo
      threads: 1
      timeout_seconds: 300
      location: europe-west4
      priority: interactive
     
      
  target: dev
